"""
Train QRC readout on one local-simulator year, then adapt/evaluate on 2026.

No QPU jobs are submitted. The 2025 training features are generated locally.
The 2026 transition/evaluation features are generated by qBraid simulator API
by default, then saved before any readout adaptation. The default workflow is:
    1. download/build SPY data;
    2. fit HAR on rows before the train year;
    3. generate local-simulator QRC features for 2025;
    4. train a Ridge readout on 2025 simulator features;
    5. generate the first 100 feature rows from 2026 on qBraid simulator;
    6. use the first transition rows to adapt only the readout;
    7. evaluate on the remaining 2026 rows.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
import yfinance as yf
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from qbraid_files.qbraid_utils import (
    build_qrc_circuit,
    counts_to_z,
    extract_counts,
    generate_j,
    local_z_expectations,
)


DEFAULT_FEATURE_DIR = THIS_DIR / "results"
DEFAULT_FIG = THIS_DIR / "figs/SPY_scaled_qbraid_transition.png"
DEFAULT_PRED = THIS_DIR / "results/SPY_scaled_qbraid_transition_predictions.csv"
DEFAULT_QBRAID_DEVICE = "ionq:ionq:sim:simulator"


def download_spy(start: str, end: str) -> pd.DataFrame:
    data = yf.download("SPY", start=start, end=end, auto_adjust=True, progress=False)
    if data.empty:
        raise RuntimeError(
            f"Yahoo Finance returned no SPY rows for {start} -> {end}. "
            "Try passing --end as a non-future market date."
        )
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)
    data = data[["Open", "High", "Low", "Close", "Volume"]].dropna()
    data.index = pd.to_datetime(data.index)
    data = data.reset_index().rename(columns={"Date": "date"})
    data.insert(1, "ticker", "SPY")
    return data


def add_targets(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["date"] = pd.to_datetime(frame["date"])
    frame = frame.sort_values("date")

    log_hl = np.log(frame["High"] / frame["Low"])
    log_co = np.log(frame["Close"] / frame["Open"])
    frame["RV"] = 0.5 * log_hl**2 - (2 * np.log(2) - 1) * log_co**2
    frame = frame[frame["RV"] > 1e-12].copy()
    frame["y"] = np.log(frame["RV"])

    frame["y_d"] = frame["y"].shift(1)
    frame["y_w"] = frame["y"].rolling(window=5).mean().shift(1)
    frame["y_m"] = frame["y"].rolling(window=22).mean().shift(1)
    frame["y_next"] = frame["y"].shift(-1)
    return frame.dropna(subset=["y_d", "y_w", "y_m", "y_next"]).copy()


def add_har(frame: pd.DataFrame, train_year: int) -> pd.DataFrame:
    frame = frame.copy()
    har_fit_rows = frame[frame["date"].dt.year < train_year].copy()
    if len(har_fit_rows) < 50:
        raise ValueError("Need more pre-train rows to fit HAR.")

    x_har = sm.add_constant(har_fit_rows[["y_d", "y_w", "y_m"]], has_constant="add")
    har = sm.OLS(har_fit_rows["y_next"], x_har).fit()

    x_all = sm.add_constant(frame[["y_d", "y_w", "y_m"]], has_constant="add")
    frame["y_hat_HAR"] = har.predict(x_all)
    frame["residual"] = frame["y_next"] - frame["y_hat_HAR"]
    return frame


def select_feature_rows(frame: pd.DataFrame, start, end=None, max_rows=None):
    subset = frame[frame["date"] >= pd.Timestamp(start)].copy()
    if end is not None:
        subset = subset[subset["date"] <= pd.Timestamp(end)]
    subset = subset.sort_values("date")
    if max_rows is not None:
        subset = subset.head(max_rows + 1)
    if len(subset) < 2:
        raise ValueError(f"Need at least two rows after {start}.")
    return subset.reset_index(drop=True)


def build_feature_csv(rows: pd.DataFrame, args, out_path: Path, backend: str) -> pd.DataFrame:
    usable_steps = len(rows) - 1
    done_steps = 0
    previous_z = np.zeros(args.num_qubits, dtype=float)
    if out_path.exists() and not args.overwrite_features:
        existing = pd.read_csv(out_path)
        if not existing.empty:
            z_cols = [f"z{idx}" for idx in range(args.num_qubits)]
            if all(col in existing.columns for col in z_cols):
                done_steps = min(len(existing), usable_steps)
                previous_z = existing.iloc[done_steps - 1][z_cols].to_numpy(dtype=float)
                if done_steps >= usable_steps:
                    print(f"Using existing features: {out_path}")
                    return existing.head(usable_steps).copy()
                print(f"Resuming {out_path} from row {done_steps}/{usable_steps}")
            else:
                raise ValueError(f"Existing feature file has incompatible z columns: {out_path}")
    elif args.overwrite_features and out_path.exists():
        out_path.unlink()

    j_mat = generate_j(args.num_qubits, args.seed)

    device = None
    if backend == "qbraid":
        from qbraid.runtime import QbraidProvider

        provider = QbraidProvider(api_key=os.getenv("QBRAID_API_KEY"))
        device = provider.get_device(args.qbraid_device_id)
        print(f"qBraid simulator for eval features: {args.qbraid_device_id}", flush=True)

    for step in range(done_steps, usable_steps):
        current = rows.iloc[step]
        target = rows.iloc[step + 1]
        counts = None
        if backend == "local":
            job_id = "local"
            z_values = local_z_expectations(
                args.num_qubits,
                j_mat,
                float(current["residual"]),
                previous_z,
                args.dt,
                args.f_b,
                args.n_trotter,
                args.input_scale,
                args.feedback_scale,
            )
        elif backend == "qbraid":
            circuit = build_qrc_circuit(
                args.num_qubits,
                j_mat,
                float(current["residual"]),
                previous_z,
                args.dt,
                args.f_b,
                args.n_trotter,
                args.input_scale,
                args.feedback_scale,
            )
            job = device.run(circuit, shots=args.qbraid_shots)
            job_id = str(getattr(job, "id", "unknown"))
            print(f"[2026 qBraid {step + 1}/{usable_steps}] submitted {job_id}", flush=True)
            result = job.result()
            counts = extract_counts(result)
            z_values = counts_to_z(counts, args.num_qubits)
        else:
            raise ValueError(f"Unknown feature backend: {backend}")

        previous_z = z_values

        rec = {
            "step": step,
            "date": current["date"].date().isoformat(),
            "target_date": target["date"].date().isoformat(),
            "ticker": "SPY",
            "split": "sim",
            "y_t": float(current["y_next"]),
            "y_har_t": float(current["y_hat_HAR"]),
            "residual_t": float(current["residual"]),
            "y_target": float(target["y_next"]),
            "y_har_target": float(target["y_hat_HAR"]),
            "residual_target": float(target["residual"]),
            "device_id": "local" if backend == "local" else args.qbraid_device_id,
            "job_id": job_id,
            "shots": 0 if backend == "local" else args.qbraid_shots,
            "num_qubits": args.num_qubits,
            "dt": args.dt,
            "f_b": args.f_b,
            "n_trotter": args.n_trotter,
            "input_scale": args.input_scale,
            "feedback_scale": args.feedback_scale,
        }
        for idx, value in enumerate(z_values):
            rec[f"z{idx}"] = float(value)
        if counts is not None:
            rec["counts_json"] = str(dict(counts))

        out_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame([rec]).to_csv(
            out_path,
            mode="a",
            header=not out_path.exists(),
            index=False,
        )
        if backend == "local" and ((step + 1) % 25 == 0 or step == 0):
            print(f"[2025 local {step + 1}/{usable_steps}] feature generated", flush=True)

    return pd.read_csv(out_path).head(usable_steps).copy()


def z_columns(frame: pd.DataFrame):
    return sorted(
        [col for col in frame.columns if col.startswith("z") and col[1:].isdigit()],
        key=lambda col: int(col[1:]),
    )


def print_feature_diagnostics(label: str, frame: pd.DataFrame, feature_cols):
    values = frame[feature_cols].to_numpy(dtype=float)
    mean = values.mean(axis=0)
    std = values.std(axis=0)
    print(f"{label} feature mean: {np.round(mean, 4)}")
    print(f"{label} feature std:  {np.round(std, 4)}")
    if float(std.max()) < 1.0e-3:
        print(f"WARNING: {label} features are nearly constant; transition is not reliable.")


def anchored_transition(w, b, x, y, anchor_l2):
    x_aug = np.column_stack([x, np.ones(len(x))])
    beta_anchor = np.concatenate([w, [b]])
    penalty = np.eye(x_aug.shape[1]) * anchor_l2
    lhs = x_aug.T @ x_aug + penalty
    rhs = x_aug.T @ y + anchor_l2 * beta_anchor
    beta = np.linalg.solve(lhs, rhs)
    return beta[:-1], float(beta[-1])


def qlike(y_true_log, y_pred_log):
    log_ratio = np.clip(np.asarray(y_true_log) - np.asarray(y_pred_log), -50.0, 50.0)
    ratio = np.exp(log_ratio)
    return float(np.mean(ratio - np.log(ratio) - 1.0))


def metrics(y_true, pred):
    mse = mean_squared_error(y_true, pred)
    return {
        "mse": float(mse),
        "rmse": float(np.sqrt(mse)),
        "mae": float(mean_absolute_error(y_true, pred)),
        "qlike": qlike(y_true, pred),
    }


def print_metrics(label, values):
    print(
        f"{label:>18s}  MSE: {values['mse']:.4f}  "
        f"RMSE: {values['rmse']:.4f}  MAE: {values['mae']:.4f}  "
        f"QLIKE: {values['qlike']:.5f}"
    )


def plot_predictions(preds: pd.DataFrame, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(preds["target_date"], preds["y_target"], color="steelblue", lw=1.1,
            alpha=0.65, label="Actual")
    ax.plot(preds["target_date"], preds["y_har_target"], color="darkorange", lw=1.2,
            label=f"HAR ({qlike(preds.y_target, preds.y_har_target):.3f})")
    ax.plot(preds["target_date"], preds["y_qrc_before"], color="seagreen", lw=1.1,
            label=f"sim readout ({qlike(preds.y_target, preds.y_qrc_before):.3f})")
    ax.plot(preds["target_date"], preds["y_qrc_after"], color="crimson", lw=1.2,
            label=f"transition readout ({qlike(preds.y_target, preds.y_qrc_after):.3f})")
    ax.set_title("SPY readout trained on 2025 simulator, adapted on 2026 transition")
    ax.set_xlabel("Date")
    ax.set_ylabel("log RV")
    ax.legend(loc="upper left", fontsize=9)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", default="2024-01-01")
    parser.add_argument("--end", default="2026-07-26")
    parser.add_argument("--train-year", type=int, default=2025)
    parser.add_argument("--eval-start", default="2026-01-01")
    parser.add_argument("--eval-rows", type=int, default=100)
    parser.add_argument("--transition-size", type=int, default=10)
    parser.add_argument("--eval-feature-backend", choices=["qbraid", "local"], default="qbraid")
    parser.add_argument("--qbraid-device-id", default=DEFAULT_QBRAID_DEVICE)
    parser.add_argument("--qbraid-shots", type=int, default=100)
    parser.add_argument("--overwrite-features", action="store_true")
    parser.add_argument("--num-qubits", type=int, default=10)
    parser.add_argument("--n-trotter", type=int, default=2)
    parser.add_argument("--dt", type=float, default=0.5)
    parser.add_argument("--f-b", type=float, default=1.0)
    parser.add_argument("--input-scale", type=float, default=1.0)
    parser.add_argument("--feedback-scale", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--ridge-alpha", type=float, default=1.0e-6)
    parser.add_argument("--anchor-l2", type=float, default=100.0)
    parser.add_argument("--feature-dir", type=Path, default=DEFAULT_FEATURE_DIR)
    parser.add_argument("--predictions", type=Path, default=DEFAULT_PRED)
    parser.add_argument("--figure", type=Path, default=DEFAULT_FIG)
    args = parser.parse_args()

    raw = download_spy(args.start, args.end)
    frame = add_har(add_targets(raw), args.train_year)

    train_rows = select_feature_rows(
        frame,
        start=f"{args.train_year}-01-01",
        end=f"{args.train_year}-12-31",
    )
    eval_rows = select_feature_rows(frame, start=args.eval_start, max_rows=args.eval_rows)

    train_features_path = (
        args.feature_dir
        / f"SPY_{args.train_year}_local_{args.num_qubits}q_train_features.csv"
    )
    eval_backend_slug = (
        "local"
        if args.eval_feature_backend == "local"
        else args.qbraid_device_id.replace(":", "_")
    )
    eval_features_path = (
        args.feature_dir
        / f"SPY_2026_{eval_backend_slug}_{args.num_qubits}q_first{args.eval_rows}_features.csv"
    )

    train_features = build_feature_csv(train_rows, args, train_features_path, backend="local")
    eval_features = build_feature_csv(
        eval_rows,
        args,
        eval_features_path,
        backend=args.eval_feature_backend,
    )

    feature_cols = z_columns(train_features)
    print_feature_diagnostics("train", train_features, feature_cols)
    print_feature_diagnostics("eval", eval_features, feature_cols)
    scaler = StandardScaler()
    x_train = scaler.fit_transform(train_features[feature_cols].to_numpy(dtype=float))
    y_train = train_features["residual_target"].to_numpy(dtype=float)

    ridge = Ridge(alpha=args.ridge_alpha)
    ridge.fit(x_train, y_train)
    w_sim = ridge.coef_.astype(float)
    b_sim = float(ridge.intercept_)

    transition_size = min(args.transition_size, max(1, len(eval_features) - 1))
    transition = eval_features.iloc[:transition_size].copy()
    test = eval_features.iloc[transition_size:].copy()

    x_transition = scaler.transform(transition[feature_cols].to_numpy(dtype=float))
    y_transition = transition["residual_target"].to_numpy(dtype=float)
    x_test = scaler.transform(test[feature_cols].to_numpy(dtype=float))

    w_after, b_after = anchored_transition(
        w_sim,
        b_sim,
        x_transition,
        y_transition,
        args.anchor_l2,
    )

    test = test.copy()
    test["target_date"] = pd.to_datetime(test["target_date"])
    test["y_qrc_before"] = test["y_har_target"] + (x_test @ w_sim + b_sim)
    test["y_qrc_after"] = test["y_har_target"] + (x_test @ w_after + b_after)

    args.predictions.parent.mkdir(parents=True, exist_ok=True)
    test.to_csv(args.predictions, index=False)
    plot_predictions(test, args.figure)

    print(f"Train year rows:      {len(train_features)}")
    print(f"2026 feature rows:    {len(eval_features)}")
    print(f"Transition rows:      {len(transition)}")
    print(f"2026 test rows:       {len(test)}")
    print(f"Feature columns:      {feature_cols}")
    print()
    print_metrics("HAR only", metrics(test["y_target"], test["y_har_target"]))
    print_metrics("sim readout", metrics(test["y_target"], test["y_qrc_before"]))
    print_metrics("transition", metrics(test["y_target"], test["y_qrc_after"]))
    print()
    print(f"Saved train features: {train_features_path}")
    print(f"Saved 2026 features:  {eval_features_path}")
    print(f"Saved predictions:    {args.predictions}")
    print(f"Saved figure:         {args.figure}")


if __name__ == "__main__":
    main()
