# -*- coding: utf-8 -*-
"""Readout.ipynb

Automatically generated by Colab.

Original file is located at
"""



from itertools import combinations

import numpy as np
from sklearn.linear_model import Ridge

__all__ = ["RidgeReadout"]


class RidgeReadout:

    def __init__(self, n_qubits: int, alpha: float = 1e-6, pair: bool = False,
                 n_reservoirs: int = 1, **ridge_kwargs):

        if n_qubits < 1:
            raise ValueError("n_qubits phải >= 1")

        self.n_qubits = n_qubits
        self.n_single = n_qubits
        self.n_pair = n_qubits * (n_qubits - 1) // 2
        self.n_reservoirs = n_reservoirs
 
        per_reservoir = self.n_single + (self.n_pair if pair else 0)
        self.in_dim = per_reservoir * n_reservoirs
        self.ridge_model = Ridge(alpha=alpha, **ridge_kwargs)

    def _check_dim(self, obs: np.ndarray) -> None:
        if obs.shape[-1] != self.in_dim:
            raise ValueError(
                f"Expected {self.in_dim} features cho {self.n_qubits} qubit "
                f"(gồm {self.n_single} <Zi> + {self.n_pair} <ZiZj>), "
                f"nhưng obs có {obs.shape[-1]} features."
            )

    def weight_output(self, obs, y_train):
        """
        Args:
            obs_train: array-like [T, in_dim]
            y_train: array-like [T] (hoặc [T, out_dim], hiện không dùng)
        Returns:
            weights của ridge regression, shape = (in_dim,)
        """
        y_train = np.asarray(y_train, dtype=float).ravel()
        obs = np.asarray(obs)
        assert obs.shape[0] == y_train.shape[0]
        self._check_dim(obs)
        self.ridge_model.fit(obs, y_train)
        self._fitted = True
        return self.ridge_model.coef_ # W_out has dim 1 x d
    
    def predict(self, obs):
        """
        Args:
            obs: [in_dim] (mot buoc) hoac [N, in_dim] (batch).
        Returns:
            e^hat float neu input 1 buoc, np.ndarray [N] neu batch.
        """
        if not self._fitted:
            raise RuntimeError("Ridge readout chưa được fit. Hãy gọi weight_output() trước.")
        obs = np.asarray(obs)
        single_step = obs.ndim == 1 # Whether it is only 1 vector
        if single_step:
            obs = obs.reshape(1, -1)
        else:
            assert obs.ndim == 2
        self._check_dim(obs)
        residual = self.ridge_model.predict(obs)
        if single_step:
            return residual[0]
        return residual
        
        

    def split_features(self, obs):
        """Tách obs thành phần <Zi> và <ZiZj> riêng để phân tích/debug."""
        obs = np.asarray(obs)
        self._check_dim(obs)
        z = obs[..., : self.n_single]
        zz = obs[..., self.n_single :]
        return z, zz

    def feature_names(self):
        names = [f"Z{i}" for i in range(self.n_qubits)]
        names += [f"Z{i}Z{j}" for i, j in combinations(range(self.n_qubits), 2)]
        return names

    def __repr__(self):
        return (
            f"RidgeReadout(n_qubits={self.n_qubits}, "
            f"in_dim={self.in_dim}, alpha={self.ridge_model.alpha})"
        )


if __name__ == "__main__":
    rng = np.random.default_rng(0)
    n_qubits = 6
    T_horizon = 20
    
    readout = RidgeReadout(n_qubits=n_qubits, alpha=1e-6, pair = False)
    print(readout)
    print("feature_names:", readout.feature_names())

    obs = rng.uniform(-1, 1, size=(T_horizon, readout.in_dim)) # this is feature vector from resevoir computing T x d
    y_train = rng.uniform(-1, 1, size=T_horizon) # Length of time horizon
    y_HAR = y_train + rng.normal(0, 0.1, T_horizon)   # HAR forecast (precomputed)
    
    # head A learns residual, not learning y directly 
    residuals = y_train - y_HAR
    W_out = readout.weight_output(obs, residuals)
    print("W_out:", W_out)
    
    print("Residual at time t is:", readout.predict(obs))
    
    
    # obs_test = rng.uniform(-1, 1, size=(5, readout.in_dim))

